import SwiftUI

struct TermsOfUseView: View {
    @Environment(\.dismiss) var dismiss
    
    let termsContent = """
TERMS OF USE (TERMS OF SERVICE)
Last Updated: 6 Feb, 2026

1. Acceptance of Terms
By accessing the VSTEP Writing Learning Website, you agree to be bound by these Terms. If you do not agree, please do not use the service. This project is an academic product created by students for educational purposes.

2. Educational Purpose & Disclaimer
• Simulation Only: This website simulates the VSTEP writing examination format (60-minute timer, word count constraints) for practice purposes.
• AI Scoring Limitation: The scores and feedback provided are generated by Artificial Intelligence (AI). While we strive to align these with official VSTEP criteria (Task Fulfillment, Organization, Vocabulary, Grammar), the AI's evaluation is estimative and does not guarantee the same score in an official VSTEP examination administered by authorized institutions (e.g., ULIS-VNU, Hue University, etc.).
• Not an Official Certification: This platform does not issue valid VSTEP certificates. Official certificates are only issued by the 38 universities authorized by the Ministry of Education and Training (MoET).

3. User Conduct
You agree not to:
• Submit content that is offensive, hate speech, or violates academic integrity (plagiarism). We utilize input filters to reject such content (Business Rule BR-14).
• Attempt to disrupt the servers (DoS attacks) or exploit the API.
• Use the "Guest" feature to spam the AI system.

4. Intellectual Property
• Your Content: You retain ownership of the essays you write. By submitting them, you grant us a license to process them for grading and display them on your dashboard.
• Our Content: The interface, code, and template database are the property of Vinhhaphoi.

5. Limitation of Liability
To the maximum extent permitted by law, the development team and the supervisors shall not be liable for any direct, indirect, or consequential damages arising from your use of this service, including but not limited to discrepancies between our AI scores and your real exam results.

6. Changes to Terms
We reserve the right to modify these terms at any time. Continued use of the website constitutes acceptance of the new terms.
"""
    
    var body: some View {
        NavigationStack {
            ScrollView {
                Text(termsContent)
                    .padding()
                    .font(.body)
                    .textSelection(.enabled)
            }
            .navigationTitle("Terms of Use")
            .navigationBarTitleDisplayMode(.large)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Close") {
                        dismiss()
                    }
                }
            }
        }
    }
}
